// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7y2lnc5LpoWFZze01o63bJNk3vWnv7Jw',
    appId: '1:746009613230:web:6b98124e465532427bae3f',
    messagingSenderId: '746009613230',
    projectId: 'dbprova-b0771',
    authDomain: 'dbprova-b0771.firebaseapp.com',
    storageBucket: 'dbprova-b0771.appspot.com',
    measurementId: 'G-DM7J4EQWV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdF89oIvw8VuJQLgrGODOr74si3KlzmSE',
    appId: '1:746009613230:android:cc709a3ceae7eedb7bae3f',
    messagingSenderId: '746009613230',
    projectId: 'dbprova-b0771',
    storageBucket: 'dbprova-b0771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL5DoHX2gcXw2ol01ZpDO4kvh53KdslIY',
    appId: '1:746009613230:ios:3e47f3e18b4991207bae3f',
    messagingSenderId: '746009613230',
    projectId: 'dbprova-b0771',
    storageBucket: 'dbprova-b0771.appspot.com',
    iosBundleId: 'com.example.prenotazione',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL5DoHX2gcXw2ol01ZpDO4kvh53KdslIY',
    appId: '1:746009613230:ios:3e47f3e18b4991207bae3f',
    messagingSenderId: '746009613230',
    projectId: 'dbprova-b0771',
    storageBucket: 'dbprova-b0771.appspot.com',
    iosBundleId: 'com.example.prenotazione',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7y2lnc5LpoWFZze01o63bJNk3vWnv7Jw',
    appId: '1:746009613230:web:6b98124e465532427bae3f',
    messagingSenderId: '746009613230',
    projectId: 'dbprova-b0771',
    authDomain: 'dbprova-b0771.firebaseapp.com',
    storageBucket: 'dbprova-b0771.appspot.com',
    measurementId: 'G-DM7J4EQWV5',
  );
}
